FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Salesforce Partner Portal 3.0 API
This is the documentation of external APIs used by the partner portal. The interactive documentation can be found here: http://docs.partnerportal1.apiary.io/

To base url for the mocking server is: http://private-4ea14-partnerportal1.apiary-mock.com/

## Group Tokens
Provides client authentication and grant access to API using tokens

## Token [/tokens]

### Get a Token [GET]

+ Request
    + Headers

            grant_type: password
            client_id: ID
            client_secret: SECRET
            username: USER
            password: PASSWORD

+ Response 200 (application/json)
    + Attributes (object, required)
        + token: Qhwej23Jhshw (string, required)

## Group Partners
Provides different data structures for a Partner: partner information, payments, coupons sold.

## Partner [/partners/{partner_id}]

+ Parameters
    + partner_id: 0015700001moHBx (string, required)

### Get a Partner by id [GET]

+ Request
    + Headers

            Authorization: Qhwej23Jhshw

+ Response 200 (application/json)
    + Attributes
        + name: Muster AG (string, required)
        + website: www.musterag.ch (string, required)
        + address (object, required)
            + street: Musterstrasse 76 (string, required)
            + complement: Postfach 80765 (string)
            + city: Musterstadt (string, required)
            + postal_code: 6754 (string, required)
        + gps_coordinates (object, required)
            + latitude: 47.3775078 (string, required)
            + longitude: 8.5016957 (string, required)

## Payments Collection [/partners/{partner_id}/payments{?page}]

+ Parameters
    + partner_id: 0015700001moHBx (string, required)
    + page: 1 (number)

### List all Payments for a Partner [GET]
+ Request
    + Headers

            Authorization: Qhwej23Jhshw

+ Response 200 (application/json)
    + Attributes (array, required)
        + (Payment)
        + (Payment)
        + (Payment)

## Payment [/partners/{partner_id}/payments/{deal_id}]

+ Parameters
    + partner_id: 0015700001moHBx (string, required)
    + deal_id

### Show Payment's details for a Deal of the Partner [GET]
+ Request
    + Headers

            Authorization: Qhwej23Jhshw

+ Response 200 (application/json)
    + Attributes (Payment)

## Buyers Collection [/partners/{partner_id}/buyers{?page}]

+ Parameters
    + partner_id: 0015700001moHBx (string, required)
    + page: 1 (number)

### List all Coupons sold for a Partner [GET]
+ Request
    + Headers

            Authorization: Qhwej23Jhshw

+ Response 200 (application/json)
    + Attributes (array, required)
        + (CouponCollection)
        + (CouponCollection)

## Buyers Export [/partners/{partner_id}/buyers/export{?collection_id}]

+ Parameters
    + partner_id: 0015700001moHBx (string, required)
    + collection_id: 15sdf0234fTRD (string, required)

### Retrieve all Coupons sold from a collection of a Partner [GET]
+ Request
    + Headers

            Authorization: Qhwej23Jhshw

+ Response 200 (application/json)
    + Attributes (CouponCollection)

## Data Structures

### Payment (object)
+ datetime: `2015-05-05T12:30:00` (string, required)
+ collections (array, required)
    + (PaymentCollection)
    + (PaymentCollection)

### PaymentCollection (object)
+ title: Lorem ipsum dolor sit amet (string, required)
+ variants (array, required)
    + (PaymentVariant)
    + (PaymentVariant)

### PaymentVariant (object)
+ price (number, required)

### CouponCollection (object)
+ id: 1 (string, required)
+ online_date: `2015-05-05T12:30:00`(string, required)
+ title: Lorem ipsum dolor sit amet (string, required)
+ deals (array, required)
    + (CouponDeal)
    + (CouponDeal)

### CouponDeal (object)
+ id: 1 (string, required)
+ title: Lorem ipsum dolor sit amet (string, required)
+ coupons (array, required)
    + (Coupon)
    + (Coupon)
        + pin: 1234RT
    + (Coupon)
        + pin: 1234RT

### Coupon (object)
+ number: 1 (number, required)
+ code: 123487TD (string, required)
+ pin (string, required)

## Group Coupons
Allows to redeem a coupon

## Coupons Redeem [/coupons]

### Redeem a set of coupons [POST]

+ Request (application/json)
    + Headers

            Authorization: Qhwej23Jhshw

    + Attributes (array, required)
        + (RedeemedCoupon)
        + (RedeemedCoupon)

+ Response 200

## Data Structures

### RedeemedCoupon (object)
+ code: 123487TD (string, required)
+ pin (string, required)
